### ISSUE TITLE
[Error: connect ETIMEDOUT] while executing "yo mtb-app"

### ISSUE THREAD

**Issue by everthis** [amfe/or.generator-mtb-app#1]
![screen shot 2015-07-01 at 8 39 53 pm](https://cloud.githubusercontent.com/assets/3142886/8454631/a586b9b4-2031-11e5-9c94-f84b327b4c9e.png)

I tried on my computer and Linode VPS. Same error.

**Comment by Jinjiang** [comment]
Looks strange, no idea about this error. I suggest you again make sure the internet access works for `github.com` and `npmjs.com`

**Comment by hongru** [comment]
@everthis sorry about that, this generator need to request apis of `http://api.gitlab.alibaba-inc.com`. So it works only under inner-company network of Alibaba.
As it just work for our team. Maybe it should be a private project.
