### ISSUE TITLE
timeout 

### ISSUE THREAD

**Issue by wanglong167** [amfe/or.generator-mtb-app#2]
http://gitlab.alibaba-inc.com/api/v3/projects/mtb%2Flib-flexible/repository/files?private_token=fFVb1jD6ir7SB8zd8MKW&ref=master&file_path=build/flexible.js

报错了

**Comment by hongru** [comment]
@wanglong167  sorry, 这个是厂内项目，有厂内环境依赖，不该放出来的。抱歉，我先拿掉
